export const mobileApps = [
  {
    appConfig: 'apps/coach-mobile/app.config.js',
    appRole: 'coach',
    bundleIdentifier: 'com.footballplayer.coach',
    envExample: 'apps/coach-mobile/.env.example',
    gitignore: 'apps/coach-mobile/.gitignore',
    notificationIcon: 'apps/coach-mobile/assets/notification-icon.png',
    easConfig: 'apps/coach-mobile/eas.json',
    expectedName: 'Football Player Coach',
    label: 'Coach mobile',
    metadata: 'apps/coach-mobile/STORE_METADATA.md',
    metroConfig: 'apps/coach-mobile/metro.config.js',
    name: 'Coach',
    packageJson: 'apps/coach-mobile/package.json',
    packageName: 'com.footballplayer.coach',
    path: 'apps/coach-mobile',
    readme: 'apps/coach-mobile/README.md',
    scheme: 'footballplayercoach',
    slug: 'football-player-coach',
    sourceRoots: ['apps/coach-mobile/App.js', 'apps/mobile-core/src'],
    submissionChecklist: 'apps/coach-mobile/STORE_SUBMISSION_CHECKLIST.md',
    restrictedAccessCopy: 'Restricted club access.',
  },
  {
    appConfig: 'apps/parent-mobile/app.config.js',
    appRole: 'parent',
    bundleIdentifier: 'com.footballplayer.parents',
    envExample: 'apps/parent-mobile/.env.example',
    gitignore: 'apps/parent-mobile/.gitignore',
    notificationIcon: 'apps/parent-mobile/assets/notification-icon.png',
    easConfig: 'apps/parent-mobile/eas.json',
    expectedName: 'Football Player Parents',
    label: 'Parents mobile',
    metadata: 'apps/parent-mobile/STORE_METADATA.md',
    metroConfig: 'apps/parent-mobile/metro.config.js',
    name: 'Parents',
    packageJson: 'apps/parent-mobile/package.json',
    packageName: 'com.footballplayer.parents',
    path: 'apps/parent-mobile',
    readme: 'apps/parent-mobile/README.md',
    scheme: 'footballplayerparents',
    slug: 'football-player-parents',
    sourceRoots: ['apps/parent-mobile/App.js', 'apps/mobile-core/src'],
    submissionChecklist: 'apps/parent-mobile/STORE_SUBMISSION_CHECKLIST.md',
    restrictedAccessCopy: 'Restricted parent access.',
  },
]
