import { buildPdfBuffer } from '../../src/lib/pdf-builder.js'

function buildSampleHtml() {
  return `
    <html>
      <head>
        <meta charset="utf-8" />
        <title>Player Feedback PDF Test</title>
      </head>
      <body style="font-family: Arial, sans-serif; color: #142018; padding: 32px;">
        <h1 style="margin: 0 0 8px;">Player Feedback</h1>
        <p style="margin: 0 0 24px;">PDF rendering test</p>

        <section style="border: 1px solid #d7e2d3; border-radius: 16px; padding: 20px;">
          <h2 style="margin: 0 0 12px;">Sample Player</h2>
          <p><strong>Team:</strong> U12 Test Team</p>
          <p><strong>Summary:</strong> This PDF was generated by the Netlify test endpoint.</p>
          <ul>
            <li><strong>Technical:</strong> 4</li>
            <li><strong>Tactical:</strong> 3</li>
            <li><strong>Coachability:</strong> 5</li>
          </ul>
        </section>
      </body>
    </html>
  `
}

export async function handler() {
  try {
    const pdfBuffer = await buildPdfBuffer(buildSampleHtml())

    return {
      statusCode: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': 'attachment; filename="test-player-feedback.pdf"',
      },
      body: pdfBuffer.toString('base64'),
      isBase64Encoded: true,
    }
  } catch (error) {
    console.error(error)

    return {
      statusCode: 500,
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ error: error.message }),
    }
  }
}
