import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const migrationUrl = new URL('../supabase/migrations/20260714135523_calendar_event_notify_edit_repair.sql', import.meta.url)
const calendarDomainUrl = new URL('../src/lib/domain/calendar-events.js', import.meta.url)
const sessionsPageUrl = new URL('../src/pages/SessionsPage.jsx', import.meta.url)
const parentPortalPageUrl = new URL('../src/pages/ParentPortalPage.jsx', import.meta.url)
const calendarInvitesDomainUrl = new URL('../src/lib/domain/calendar-event-invites.js', import.meta.url)
const notificationStatusUrl = new URL('../src/lib/domain/calendar-notification-status.js', import.meta.url)

const [migration, calendarDomain, sessionsPage, parentPortalPage, calendarInvitesDomain, notificationStatus] = await Promise.all([
  readFile(migrationUrl, 'utf8'),
  readFile(calendarDomainUrl, 'utf8'),
  readFile(sessionsPageUrl, 'utf8'),
  readFile(parentPortalPageUrl, 'utf8'),
  readFile(calendarInvitesDomainUrl, 'utf8'),
  readFile(notificationStatusUrl, 'utf8'),
])

test('Calendar revisions are generated by the database and ignore no-op double saves', () => {
  assert.match(migration, /add column if not exists notification_revision bigint not null default 1/i)
  assert.match(migration, /row\([\s\S]*new\.title[\s\S]*new\.starts_at[\s\S]*new\.parent_audience[\s\S]*\) is distinct from row\(/i)
  assert.match(migration, /new\.notification_revision = old\.notification_revision \+ 1/i)
  assert.match(migration, /else[\s\S]*new\.notification_revision = old\.notification_revision/i)
  assert.match(migration, /before update on public\.calendar_events/i)
})

test('notification identity allows later revisions while deduplicating retries per recipient', () => {
  assert.match(migration, /calendar_event_id,[\s\S]*event_revision,[\s\S]*notification_type,[\s\S]*lower\(recipient_email\)/i)
  assert.match(migration, /calendar-event:', event_record\.id[\s\S]*':revision:', event_record\.notification_revision/i)
  assert.match(migration, /if notification_record\.status = 'queued'[\s\S]*duplicate_count := duplicate_count \+ 1/i)
  assert.match(migration, /status = 'failed'[\s\S]*last_error = left\(sqlerrm, 1000\)/i)
  assert.match(migration, /notification_record\.status = 'queued'[\s\S]*continue/i)
})

test('the server verifies staff, club, team, plan, audience, and current event state', () => {
  assert.match(migration, /if auth\.uid\(\) is null/i)
  assert.match(migration, /actor\.role in \('parent_portal', 'super_admin'\)/i)
  assert.match(migration, /coalesce\(actor\.status, 'active'\) <> 'active'/i)
  assert.match(migration, /coalesce\(actor\.role_rank, 0\) < 20/i)
  assert.match(migration, /calendar_event\.club_id = actor\.club_id/i)
  assert.match(migration, /from public\.team_staff staff[\s\S]*staff\.team_id = event_record\.team_id[\s\S]*staff\.user_id = actor\.id/i)
  assert.match(migration, /event_record\.cancelled_at is not null/i)
  assert.match(migration, /event_record\.parent_audience not in \('involved_players', 'all_team_parents'\)/i)
  assert.match(migration, /can_use_plan_feature\(event_record\.club_id, 'parentPortal'\)/i)
  assert.match(migration, /can_use_plan_feature\(event_record\.club_id, 'parentEmails'\)/i)
})

test('involved player scope is validated while team-wide recipient scope is rebuilt server-side', () => {
  assert.match(migration, /event_record\.parent_audience = 'all_team_parents'[\s\S]*from public\.players player[\s\S]*player\.team_id = event_record\.team_id/i)
  assert.match(migration, /requested_player_count[\s\S]*from unnest\(coalesce\(player_ids_value/i)
  assert.match(migration, /selected_player_count <> requested_player_count/i)
  assert.match(migration, /outside this event team or are no longer active/i)
  assert.match(migration, /link\.status = 'active'/i)
  assert.match(migration, /link\.auth_user_id is not null/i)
  assert.match(migration, /distinct on \(lower\(btrim\(link\.email\)\)\)/i)
  assert.match(migration, /'to', jsonb_build_array\(recipient\.recipient_email\)/i)
  assert.doesNotMatch(migration, /string_agg\([^)]*recipient_email/i)
})

test('notify creates or updates one informational Portal record per event and child', () => {
  assert.match(migration, /on conflict \(club_id, player_id, calendar_event_id, assessment_session_id\) do update/i)
  assert.match(migration, /invite\.player_id <> all\(selected_player_ids\)[\s\S]*invite_status <> 'cancelled'/i)
  assert.match(migration, /notify_requested = true/i)
  assert.match(migration, /when public\.calendar_event_invites\.responded_at is not null then public\.calendar_event_invites\.invite_status/i)
  assert.doesNotMatch(migration, /responded_at\s*=\s*null/i)
  assert.match(calendarInvitesDomain, /existingRow\?\.responded_at \? existingRow\.invite_status : 'active'/i)
  assert.match(migration, /'responseRequirement', 'informational'/i)
})

test('creation and update emails use latest saved fields and a safe event destination', () => {
  assert.match(migration, /New event added:/i)
  assert.match(migration, /Event details updated:/i)
  assert.match(migration, /event_record\.title/i)
  assert.match(migration, /event_record\.starts_at/i)
  assert.match(migration, /event_record\.ends_at/i)
  assert.match(migration, /event_record\.location/i)
  assert.match(migration, /event_record\.notes/i)
  assert.match(migration, /No response is required\. This event is informational\./i)
  assert.match(migration, /Your existing response remains unchanged\. No new response is required\./i)
  assert.match(migration, /parent\.footballplayer\.online\/parent-portal\?section=calendar&eventId=/i)
  assert.match(migration, /View event details/i)
})

test('Portal state commits before isolated email failures and results stay structured', () => {
  const portalUpsert = migration.indexOf('insert into public.calendar_event_invites')
  const queueInsert = migration.indexOf('insert into public.scheduled_email_queue')

  assert.ok(portalUpsert > 0)
  assert.ok(queueInsert > portalUpsert)
  assert.match(migration, /begin[\s\S]*insert into public\.scheduled_email_queue[\s\S]*exception[\s\S]*when others then/i)
  assert.match(migration, /portal_ready_email_partial/i)
  assert.match(migration, /portal_ready_no_eligible_email/i)
  assert.match(migration, /'portalCreatedCount'/i)
  assert.match(migration, /'portalUpdatedCount'/i)
  assert.match(migration, /'queuedCount'/i)
  assert.match(migration, /'failedCount'/i)
  assert.match(migration, /'duplicateCount'/i)
})

test('the ledger and internal helper are not exposed to browser roles', () => {
  assert.match(migration, /enable row level security/i)
  assert.match(migration, /revoke all privileges on table public\.calendar_event_notification_events from public, anon, authenticated/i)
  assert.match(migration, /revoke all on function public\.calendar_event_notification_escape_html\(text\) from public, anon, authenticated/i)
  assert.match(migration, /revoke all on function public\.notify_calendar_event_parents\(uuid, text, uuid\[\]\) from public/i)
  assert.match(migration, /revoke execute on function public\.notify_calendar_event_parents\(uuid, text, uuid\[\]\) from anon/i)
  assert.match(migration, /grant execute on function public\.notify_calendar_event_parents\(uuid, text, uuid\[\]\) to authenticated, service_role/i)
  assert.match(migration, /security definer[\s\S]*set search_path = ''/i)
})

test('Calendar create and edit call the authoritative command after saving the event', () => {
  const saveIndex = sessionsPage.indexOf("await updateCalendarEvent")
  const notifyIndex = sessionsPage.indexOf('await notifyCalendarEventParents')

  assert.ok(saveIndex > 0)
  assert.ok(notifyIndex > 0)
  assert.match(calendarDomain, /supabase\.rpc\('notify_calendar_event_parents'/i)
  assert.match(calendarDomain, /calendar_event_id_value: normalizedEventSource === 'calendar' \? normalizedEventId : null/i)
  assert.match(calendarDomain, /notification_request_token_value: normalizedRequestToken/i)
  assert.match(calendarDomain, /supabase\.rpc\('sync_calendar_event_parent_scope_v2'[\s\S]*player_ids_value: normalizedSelectionMode === 'whole_squad' \? \[\] : normalizedPlayerIds/i)
  assert.match(calendarDomain, /supabase\.rpc\('notify_calendar_event_parents'[\s\S]*player_ids_value: \[\]/i)
  assert.match(sessionsPage, /eventAction: sourceType === 'calendar' \|\| sourceType === 'match-day' \? 'update' : 'creation'/i)
  assert.match(sessionsPage, /nextCalendarInvites = await getCalendarEventInvites\(\{ user \}\)/i)
})

test('edit notification is opt-in every time and communicates partial states precisely', () => {
  const formInviteStart = sessionsPage.indexOf('function getFormInviteFields')
  const formInviteEnd = sessionsPage.indexOf('\nfunction ', formInviteStart + 1)
  const formInviteSource = sessionsPage.slice(formInviteStart, formInviteEnd)

  assert.match(formInviteSource, /notifyInvitedFamilies: false/i)
  assert.doesNotMatch(formInviteSource, /some\(\(invite\) => invite\.notifyRequested\)/i)
  assert.match(notificationStatus, /parent email[\s\S]*sent/i)
  assert.match(sessionsPage, /Event saved, parent notification incomplete/i)
  assert.match(notificationStatus, /parent emails could not be sent\. Please try again/i)
  assert.match(notificationStatus, /no eligible parent email addresses were available/i)
  assert.match(sessionsPage, /Parents will see the event in their Parent Portal and receive an email notification\./i)
  assert.doesNotMatch(sessionsPage, /holding queue/i)
})

test('the Parent Portal deep link selects only an authorised relationship and opens the saved event', () => {
  assert.match(parentPortalPage, /searchParams\.get\('parentLinkId'\)/i)
  assert.match(parentPortalPage, /links\.some\(\(link\) => link\.id === requestedParentLinkId\)/i)
  assert.match(parentPortalPage, /searchParams\.get\('eventId'\)/i)
  assert.match(parentPortalPage, /parentCalendarEvents\.find\(\(event\) => String\(event\.sourceId\) === requestedEventId\)/i)
  assert.match(parentPortalPage, /setSelectedCalendarEventId\(requestedEvent\.id\)/i)
})

test('audit metadata records revision, Portal, queue, and final state without recipient addresses', () => {
  const auditStart = migration.indexOf("'calendar_event_parent_notification_requested'")
  const auditEnd = migration.indexOf("return jsonb_build_object", auditStart)
  const auditSource = migration.slice(auditStart, auditEnd)

  assert.match(auditSource, /eventRevision/i)
  assert.match(auditSource, /notificationType/i)
  assert.match(auditSource, /portalCreatedCount/i)
  assert.match(auditSource, /eligibleRecipientCount/i)
  assert.match(auditSource, /queuedCount/i)
  assert.match(auditSource, /failedCount/i)
  assert.match(auditSource, /idempotencyPrefix/i)
  assert.match(auditSource, /finalState/i)
  assert.doesNotMatch(auditSource, /recipientEmail/i)
})
