import { migrationSourceUrl } from './helpers/migration-source.mjs'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { test } from 'node:test'

const migrationUrl = migrationSourceUrl('20260630123924_20260630121322_matchday_parent_response_roles.sql', 'active')
const repairMigrationUrl = migrationSourceUrl('20260630130248_20260630125915_repair_matchday_parent_response_rpc.sql', 'active')
const sharedModelMigrationUrl = migrationSourceUrl('20260630155720_20260630153247_matchday_availability_shared_model.sql', 'active')
const parentRoleStateMigrationUrl = migrationSourceUrl('20260701084026_matchday_parent_role_selection_state.sql', 'active')
const transportResponseMigrationUrl = new URL('../supabase/migrations/20260704145027_matchday_transport_response_fields.sql', import.meta.url)
const sendFunctionUrl = new URL('../netlify/functions/send-match-day-availability-requests.js', import.meta.url)
const selectVolunteerFunctionUrl = new URL('../netlify/functions/select-match-day-volunteer.js', import.meta.url)
const confirmFunctionUrl = new URL('../netlify/functions/match-day-availability-confirm.js', import.meta.url)
const domainUrl = new URL('../src/lib/domain/match-day.js', import.meta.url)
const staffPageUrl = new URL('../src/pages/MatchDayPage.jsx', import.meta.url)
const parentPortalPageUrl = new URL('../src/pages/ParentPortalPage.jsx', import.meta.url)

test('migration adds parent availability volunteer response storage', async () => {
  const migration = await readFile(migrationUrl, 'utf8')

  assert.match(migration, /add column if not exists parent_link_id uuid references public\.parent_player_links/i)
  assert.match(migration, /add column if not exists volunteer_scorer_response text not null default 'no_response'/i)
  assert.match(migration, /add column if not exists volunteer_linesman_response text not null default 'no_response'/i)
  assert.match(migration, /add column if not exists volunteer_referee_response text not null default 'no_response'/i)
  assert.match(migration, /add column if not exists volunteer_responded_at timestamptz/i)
  assert.match(migration, /check \(volunteer_scorer_response in \('no_response', 'yes', 'no'\)\)/i)
})

test('migration keeps token response writes behind security definer RPCs', async () => {
  const migration = await readFile(migrationUrl, 'utf8')

  assert.match(migration, /create or replace function public\.get_match_day_availability_response\(token_hash_value text\)[\s\S]*security definer[\s\S]*set search_path = public/i)
  assert.match(migration, /create or replace function public\.submit_match_day_availability_response\([\s\S]*volunteer_scorer_response_value text default null[\s\S]*volunteer_linesman_response_value text default null[\s\S]*volunteer_referee_response_value text default null/i)
  assert.match(migration, /normalized_token_hash !~ '\^\[a-f0-9\]\{64\}\$'/i)
  assert.match(migration, /normalized_status not in \('available', 'unavailable', 'maybe'\)/i)
  assert.match(migration, /grant execute on function public\.submit_match_day_availability_response\(text, text, text, text, text\) to anon;/i)
  assert.match(migration, /grant execute on function public\.submit_match_day_availability_response\(text, text, text, text, text\) to authenticated;/i)
})

test('repair migration qualifies match day parent response RPC columns', async () => {
  const migration = await readFile(repairMigrationUrl, 'utf8')

  assert.match(migration, /create or replace function public\.submit_match_day_availability_response\([\s\S]*volunteer_referee_response_value text default null/i)
  assert.match(migration, /returns table \([\s\S]*volunteer_responded_at timestamptz[\s\S]*\)/i)
  assert.match(migration, /language plpgsql[\s\S]*security definer[\s\S]*set search_path = public/i)
  assert.match(migration, /update public\.match_day_availability_requests as availability[\s\S]*else availability\.volunteer_responded_at/i)
  assert.match(migration, /where availability\.id = request_row\.id/i)
  assert.match(migration, /from public\.parent_player_links as parent_link[\s\S]*where parent_link\.id = updated_row\.parent_link_id/i)
  assert.match(migration, /update public\.match_day_scorer_interest as scorer_interest[\s\S]*where scorer_interest\.match_day_id = match_row\.id/i)
  assert.match(migration, /grant execute on function public\.submit_match_day_availability_response\(text, text, text, text, text\) to anon;/i)
  assert.match(migration, /grant execute on function public\.submit_match_day_availability_response\(text, text, text, text, text\) to authenticated;/i)
  assert.doesNotMatch(migration, /drop function/i)
  assert.doesNotMatch(migration, /cascade/i)
  assert.doesNotMatch(migration, /else volunteer_responded_at/i)
})

test('migration links scorer yes replies into existing scorer selection without replacing selected parents', async () => {
  const migration = await readFile(migrationUrl, 'utf8')

  assert.match(migration, /insert into public\.match_day_scorer_interest/i)
  assert.match(migration, /on conflict \(match_day_id, parent_link_id\)[\s\S]*where public\.match_day_scorer_interest\.status <> 'selected'/i)
  assert.match(migration, /next_scorer_response = 'no'[\s\S]*set status = 'declined'/i)
})

test('migration expands parent portal matchday RPC response state safely', async () => {
  const migration = await readFile(migrationUrl, 'utf8')

  assert.match(migration, /drop function if exists public\.get_parent_portal_match_days\(uuid\);/i)
  assert.match(migration, /availability_status text[\s\S]*volunteer_scorer_response text[\s\S]*volunteer_linesman_response text[\s\S]*volunteer_referee_response text/i)
  assert.match(migration, /left join lateral \([\s\S]*from public\.match_day_availability_requests request[\s\S]*request\.parent_link_id = link\.id/i)
  assert.match(migration, /revoke execute on function public\.get_parent_portal_match_days\(uuid\) from anon;/i)
  assert.doesNotMatch(migration, /grant execute on function public\.get_parent_portal_match_days\(uuid\) to anon;/i)
})

test('shared availability migration adds current player availability and history without dropping RPCs', async () => {
  const migration = await readFile(sharedModelMigrationUrl, 'utf8')

  assert.match(migration, /create table if not exists public\.match_day_player_availability/i)
  assert.match(migration, /create table if not exists public\.match_day_player_availability_history/i)
  assert.match(migration, /create table if not exists public\.match_day_role_assignments/i)
  assert.match(migration, /create unique index if not exists match_day_player_availability_match_player_key[\s\S]*match_day_id, player_id/i)
  assert.match(migration, /constraint match_day_role_assignments_role_check check \(role in \('scorer', 'linesman', 'referee'\)\)/i)
  assert.match(migration, /order by request\.match_day_id,[\s\S]*request\.player_id,[\s\S]*request\.responded_at desc nulls last/i)
  assert.doesNotMatch(migration, /drop function/i)
})

test('parent portal role state migration exposes selected roles without broad parent data', async () => {
  const migration = await readFile(parentRoleStateMigrationUrl, 'utf8')

  assert.match(migration, /drop function if exists public\.get_parent_portal_match_days\(uuid\);/i)
  assert.match(migration, /role_assignments jsonb[\s\S]*events jsonb/i)
  assert.match(migration, /from public\.match_day_role_assignments assignment/i)
  assert.match(migration, /'isCurrentParent', assignment\.parent_link_id = parent_link_id_value/i)
  assert.match(migration, /'parentEmail', case when assignment\.parent_link_id = parent_link_id_value/i)
  assert.match(migration, /'playerName', case when assignment\.parent_link_id = parent_link_id_value/i)
  assert.match(migration, /where auth\.uid\(\) is not null[\s\S]*match_day\.parent_visible is true/i)
  assert.match(migration, /revoke execute on function public\.get_parent_portal_match_days\(uuid\) from anon;/i)
  assert.match(migration, /grant execute on function public\.get_parent_portal_match_days\(uuid\) to authenticated;/i)
  assert.doesNotMatch(migration, /grant execute on function public\.get_parent_portal_match_days\(uuid\) to anon;/i)
  assert.doesNotMatch(migration, /create table/i)
  assert.doesNotMatch(migration, /drop table/i)
  assert.doesNotMatch(migration, /cascade/i)
})

test('shared availability RPC preserves existing submit signature and adds a v2 read model', async () => {
  const migration = await readFile(sharedModelMigrationUrl, 'utf8')

  assert.match(migration, /create or replace function public\.get_match_day_availability_response_v2\(token_hash_value text\)/i)
  assert.match(migration, /current_availability_status text[\s\S]*current_availability_selected_by_name text[\s\S]*current_availability_selected_by_email text/i)
  assert.match(migration, /create or replace function public\.submit_match_day_availability_response\([\s\S]*status_value text[\s\S]*volunteer_referee_response_value text default null/i)
  assert.match(migration, /returns table \([\s\S]*request_id uuid[\s\S]*volunteer_responded_at timestamptz[\s\S]*\)/i)
  assert.match(migration, /should_update_availability := normalized_status in \('available', 'unavailable', 'maybe'\)/i)
  assert.match(migration, /insert into public\.scheduled_email_queue[\s\S]*previous_current\.selected_by_email/i)
  assert.match(migration, /insert into public\.match_day_player_availability_history/i)
  assert.match(migration, /coalesce\(current_availability\.status, availability\.status\) as availability_status/i)
  assert.match(migration, /grant execute on function public\.get_match_day_availability_response_v2\(text\) to anon;/i)
  const parentPortalSignature = migration.slice(
    migration.indexOf('create or replace function public.get_parent_portal_match_days'),
    migration.indexOf('language sql', migration.indexOf('create or replace function public.get_parent_portal_match_days')),
  )
  assert.doesNotMatch(parentPortalSignature, /availability_selected_by_name text/i)
})

test('transport response migration adds structured staff-only fields and safe checks', async () => {
  const migration = await readFile(transportResponseMigrationUrl, 'utf8')

  assert.match(migration, /add column if not exists transport_needs_lift boolean not null default false/i)
  assert.match(migration, /add column if not exists transport_can_offer_lift boolean not null default false/i)
  assert.match(migration, /add column if not exists transport_seats_offered integer not null default 0/i)
  assert.match(migration, /add column if not exists transport_responded_at timestamptz/i)
  assert.match(migration, /constraint match_day_availability_transport_seats_check/i)
  assert.match(migration, /transport_seats_offered >= 0/i)
  assert.match(migration, /transport_can_offer_lift is true[\s\S]*or transport_seats_offered = 0/i)
  assert.doesNotMatch(migration, /transport_note/i)
  assert.doesNotMatch(migration, /free[-_\s]?text/i)
})

test('transport response RPCs read and store structured token response fields', async () => {
  const migration = await readFile(transportResponseMigrationUrl, 'utf8')

  assert.match(migration, /drop function if exists public\.get_match_day_availability_response_v2\(text\);/i)
  assert.match(migration, /transport_needs_lift boolean[\s\S]*transport_can_offer_lift boolean[\s\S]*transport_seats_offered integer[\s\S]*transport_responded_at timestamptz/i)
  assert.match(migration, /coalesce\(request_row\.transport_needs_lift, false\)/i)
  assert.match(migration, /transport_needs_lift_value boolean default null[\s\S]*transport_can_offer_lift_value boolean default null[\s\S]*transport_seats_offered_value integer default null/i)
  assert.match(migration, /has_transport_response := transport_needs_lift_value is not null[\s\S]*transport_seats_offered_value is not null/i)
  assert.match(migration, /when next_transport_can_offer_lift is true then greatest\(coalesce\(transport_seats_offered_value, request_row\.transport_seats_offered, 0\), 0\)[\s\S]*else 0/i)
  assert.match(migration, /transport_responded_at = case[\s\S]*when has_transport_response then timezone\('utc', now\(\)\)/i)
  assert.match(migration, /grant execute on function public\.submit_match_day_availability_response\(text, text, text, text, text, boolean, boolean, integer\) to anon;/i)
  assert.match(migration, /grant execute on function public\.submit_match_day_availability_response\(text, text, text, text, text, boolean, boolean, integer\) to authenticated;/i)
  assert.doesNotMatch(migration, /cascade/i)
})

test('send function creates one response form link and stores parent link context', async () => {
  const source = await readFile(sendFunctionUrl, 'utf8')

  assert.match(source, /\.from\('parent_player_links'\)[\s\S]*\.eq\('status', 'active'\)/)
  assert.match(source, /createSupabaseAdminClient\(event\)/)
  assert.match(source, /const \{ data: parentLinks, error: parentLinksError \} = await adminSupabase/)
  assert.match(source, /parent_link_id: parentLink\?\.id \|\| null/)
  assert.match(source, /volunteer_scorer_response: 'no_response'/)
  assert.match(source, /Open response form/)
  assert.match(source, /match-day-availability-confirm\?token=\$\{token\}/)
  assert.match(source, /\.from\('scheduled_email_queue'\)[\s\S]*\.insert\(/)
  assert.match(source, /queuedCount: queuedEmails\.length/)
  assert.match(source, /matchDayAvailabilityRequestId: request\.id/)
  assert.match(source, /getMatchDayDisplayName/)
  assert.doesNotMatch(source, /sendEmail\(/)
  assert.doesNotMatch(source, /status=available/)
})

test('confirmation function renders a form and submits availability plus role replies', async () => {
  const source = await readFile(confirmFunctionUrl, 'utf8')

  assert.match(source, /supabase\.rpc\('get_match_day_availability_response_v2'/)
  assert.match(source, /supabase\.rpc\('submit_match_day_availability_response'/)
  assert.match(source, /Keep \$\{statusLabel\(currentStatus\)\}/)
  assert.match(source, /currentAvailabilityAttribution\(response, currentStatus\)/)
  assert.match(source, /Current availability: \$\{escapeHtml\(sentenceStatusLabel\(currentStatus\)\)\}, submitted by \$\{escapeHtml\(selectedBy\)\} at \$\{escapeHtml\(selectedAt\)\}/)
  assert.match(source, /normalizeText\(response\.current_availability_selected_by_name\)[\s\S]*normalizeText\(response\.current_availability_selected_by_email\)/)
  assert.match(source, /formatReadableTimestamp\(response\.current_availability_selected_at\)/)
  assert.match(source, /status_value: VALID_STATUSES\.has\(status\) \? status : null/)
  assert.match(source, /roleFieldset\('volunteerScorerResponse', 'scorer'/)
  assert.match(source, /roleFieldset\('volunteerLinesmanResponse', 'linesman'/)
  assert.match(source, /roleFieldset\('volunteerRefereeResponse', 'referee'/)
  assert.match(source, /legacyStatus/)
  assert.match(source, /Fixture response/)
})

test('confirmation function renders Add to calendar near fixture details without maps or volunteer dependency', async () => {
  const source = await readFile(confirmFunctionUrl, 'utf8')
  const calendarStart = source.indexOf('function buildFixtureResponseCalendarUrl')
  const calendarEnd = source.indexOf('function page', calendarStart)
  const detailStart = source.indexOf('function detailRows')
  const detailEnd = source.indexOf('function currentAvailabilityAttribution', detailStart)
  const responseFormStart = source.indexOf('function responseForm')
  const responseFormEnd = source.indexOf('function normalizeVolunteerParam', responseFormStart)
  assert.notEqual(calendarStart, -1)
  assert.notEqual(calendarEnd, -1)
  assert.notEqual(detailStart, -1)
  assert.notEqual(detailEnd, -1)
  assert.notEqual(responseFormStart, -1)
  assert.notEqual(responseFormEnd, -1)

  const calendarSource = source.slice(calendarStart, calendarEnd)
  const detailSource = source.slice(detailStart, detailEnd)
  const responseFormSource = source.slice(responseFormStart, responseFormEnd)

  assert.match(calendarSource, /response\.match_date/)
  assert.match(calendarSource, /response\.arrival_time \|\| response\.kickoff_time/)
  assert.match(calendarSource, /response\.venue_address \|\| response\.venue_name/)
  assert.match(calendarSource, /https:\/\/calendar\.google\.com\/calendar\/render/)
  assert.match(calendarSource, /ctz: 'Europe\/London'/)
  assert.doesNotMatch(calendarSource, /volunteerScorerResponse|volunteerLinesmanResponse|volunteerRefereeResponse/)
  assert.match(detailSource, /const calendarUrl = buildFixtureResponseCalendarUrl\(response\)/)
  assert.match(detailSource, /<p class="calendar-action"><a href="\$\{escapeHtml\(calendarUrl\)\}" target="_blank" rel="noopener noreferrer">Add to calendar<\/a><\/p>/)
  assert.match(responseFormSource, /\$\{detailRows\(response\)\}[\s\S]*<form method="post" action="\/\.netlify\/functions\/match-day-availability-confirm">/)
  assert.match(responseFormSource, /<button type="submit">Save response<\/button>/)
  assert.doesNotMatch(detailSource, /maps|directions/i)
  assert.doesNotMatch(calendarSource, /maps|directions/i)
})

test('confirmation function captures structured transport response without free text notes', async () => {
  const source = await readFile(confirmFunctionUrl, 'utf8')

  assert.match(source, /function transportFields\(response\)/)
  assert.match(source, /name: 'transportNeedsLift'/)
  assert.match(source, /Does this player need a lift\?/)
  assert.match(source, /name: 'transportCanOfferLift'/)
  assert.match(source, /Can you offer a lift\?/)
  assert.match(source, /name="transportSeatsOffered" min="0" step="1"/)
  assert.match(source, /Staff coordinate transport manually\. These answers are not shared with other parents\./)
  assert.match(source, /function normalizeBooleanParam/)
  assert.match(source, /function normalizeSeatsParam/)
  assert.match(source, /transport_needs_lift_value: transportNeedsLift/)
  assert.match(source, /transport_can_offer_lift_value: transportCanOfferLift/)
  assert.match(source, /transport_seats_offered_value: transportSeatsOffered/)
  assert.match(source, /if \(VALID_STATUSES\.has\(submittedStatus\)\)[\s\S]*createAvailabilityEventLogEntry/)
  assert.doesNotMatch(source, /transportNote|transport_note|textarea[\s\S]*Transport/)
})

test('domain normalizer exposes staff and parent response fields', async () => {
  const source = await readFile(domainUrl, 'utf8')
  const selectVolunteerStart = source.indexOf('export async function selectMatchDayVolunteer')
  const selectVolunteerEnd = source.indexOf('export async function selectMatchDayScorer')
  const selectVolunteerSource = source.slice(selectVolunteerStart, selectVolunteerEnd)

  assert.match(source, /function normalizeAvailabilityRequest/)
  assert.match(source, /function normalizePlayerAvailability/)
  assert.match(source, /function normalizeAvailabilityHistory/)
  assert.match(source, /function normalizeRoleAssignment/)
  assert.match(source, /row\.role_assignments/)
  assert.match(source, /isCurrentParent: row\.is_current_parent === true/)
  assert.match(source, /match_day_player_availability \(\*\)/)
  assert.match(source, /match_day_player_availability_history \(\*\)/)
  assert.match(source, /match_day_role_assignments \(\*, parent_player_links:parent_link_id \(email, auth_user_id, players:player_id \(player_name\)\)\)/)
  assert.match(source, /match_day_availability_requests \(\*, players:player_id \(player_name\), parent_player_links:parent_link_id \(email, auth_user_id, players:player_id \(player_name\)\)\)/)
  assert.match(source, /availabilityStatus: normalizeText\(row\.availability_status/)
  assert.match(source, /volunteerScorerResponse: normalizeVolunteerResponse/)
  assert.match(source, /roleAssignments,/)
  assert.match(source, /playerAvailability,/)
  assert.match(source, /availabilityHistory,/)
  assert.match(source, /availabilityRequests,/)
  assert.match(selectVolunteerSource, /export async function selectMatchDayVolunteer/)
  assert.match(selectVolunteerSource, /volunteer\?\.requestId/)
  assert.match(selectVolunteerSource, /supabase\.auth\.getSession\(\)/)
  assert.match(selectVolunteerSource, /fetch\('\/\.netlify\/functions\/select-match-day-volunteer'/)
  assert.match(selectVolunteerSource, /requestId: volunteer\.requestId/)
  assert.doesNotMatch(selectVolunteerSource, /\.from\('match_day_role_assignments'\)/)
})

test('domain normalizer exposes structured transport fields safely', async () => {
  const source = await readFile(domainUrl, 'utf8')

  assert.match(source, /function normalizeNonNegativeInteger/)
  assert.match(source, /transportNeedsLift: row\.transport_needs_lift === true/)
  assert.match(source, /transportCanOfferLift,/)
  assert.match(source, /transportSeatsOffered: transportCanOfferLift[\s\S]*normalizeNonNegativeInteger\(row\.transport_seats_offered/)
  assert.match(source, /transportRespondedAt: row\.transport_responded_at/)
  assert.match(source, /updatedAt: row\.updated_at/)
})

test('staff and parent pages surface availability and volunteer responses', async () => {
  const staffSource = await readFile(staffPageUrl, 'utf8')
  const parentSource = await readFile(parentPortalPageUrl, 'utf8')

  assert.match(staffSource, /Availability/)
  assert.match(staffSource, /Parent volunteer requests/)
  assert.match(staffSource, /getCurrentAvailabilityRows/)
  assert.match(staffSource, /getAvailabilityHistoryForPlayer/)
  assert.match(staffSource, /getSelectedRoleAssignment/)
  assert.match(staffSource, /function getVolunteerSelectionReason/)
  assert.match(staffSource, /const canSelect = !selectionReason/)
  assert.match(staffSource, /Only parents who replied Yes can be selected\./)
  assert.match(staffSource, /This response cannot be assigned because the request record is missing\./)
  assert.match(staffSource, /onVolunteerSelection\(match, row, role\.key, !isSelected\)/)
  assert.match(staffSource, /getVolunteerConfirmationCopy/)
  assert.match(staffSource, /Replace the selected \$\{roleLabel\.label\.toLowerCase\(\)\} with \$\{parentName\}\?/)
  assert.match(staffSource, /onConfirm=\{handleVolunteerSelection\}/)
  assert.match(staffSource, /Response:/)
  assert.match(staffSource, /Not selected, another volunteer selected/)
  assert.match(parentSource, /Your fixture response/)
  assert.match(parentSource, /Volunteer role status/)
  assert.match(parentSource, /getParentRoleSelectionRows/)
  assert.match(parentSource, /You have been selected as \$\{roleLabel\} for this fixture\./)
  assert.match(parentSource, /Another volunteer has been selected\./)
  assert.match(parentSource, /The team has not selected anyone yet\./)
  assert.match(parentSource, /Open this fixture in Calendar or Invites to review and change active responses\./)
  assert.match(parentSource, /Existing email response links continue to work\./)
})

test('staff transport risk summary is staff only and availability derived', async () => {
  const staffSource = await readFile(staffPageUrl, 'utf8')
  const parentSource = await readFile(parentPortalPageUrl, 'utf8')
  const helperStart = staffSource.indexOf('function getTransportRiskRows')
  const helperEnd = staffSource.indexOf('function getAvailabilityStats', helperStart)
  const panelStart = staffSource.indexOf('function TransportRiskPanel')
  const panelEnd = staffSource.indexOf('function ReadinessItem', panelStart)

  assert.notEqual(helperStart, -1)
  assert.notEqual(helperEnd, -1)
  assert.notEqual(panelStart, -1)
  assert.notEqual(panelEnd, -1)

  const helperSource = staffSource.slice(helperStart, helperEnd)
  const panelSource = staffSource.slice(panelStart, panelEnd)

  assert.match(helperSource, /getCurrentAvailabilityRows\(match\)/)
  assert.match(helperSource, /getAvailabilityConflictKeys\(requests\)/)
  assert.match(helperSource, /status !== 'available'/)
  assert.match(helperSource, /key: 'no_response'/)
  assert.match(helperSource, /key: 'unavailable'/)
  assert.match(helperSource, /key: 'maybe'/)
  assert.match(helperSource, /key: 'conflict'/)
  assert.match(helperSource, /key: 'needs_lift'/)
  assert.match(helperSource, /key: 'lift_offer'/)
  assert.match(panelSource, /Transport risk/)
  assert.match(panelSource, /Derived from availability responses/)
  assert.match(panelSource, /structured transport replies/)
  assert.match(panelSource, /Staff coordinate manually/)
  assert.match(panelSource, /Needs staff follow-up/)
  assert.match(panelSource, /Needs lift/)
  assert.match(panelSource, /Lift offers/)
  assert.match(panelSource, /Seats offered:/)
  assert.match(panelSource, /Transport response recorded/)
  assert.match(panelSource, /No transport risk detected from availability responses\./)
  assert.doesNotMatch(helperSource, /fetch\(/)
  assert.doesNotMatch(helperSource, /localStorage/)
  assert.doesNotMatch(panelSource, /fetch\(/)
  assert.doesNotMatch(panelSource, /recipientEmail|selectedByEmail|parentEmail/)
  assert.doesNotMatch(parentSource, /Transport risk/)
  assert.doesNotMatch(parentSource, /Derived from availability responses/)
  assert.doesNotMatch(parentSource, /Needs staff follow-up/)
  assert.doesNotMatch(parentSource, /Needs lift|Lift offers|Can offer lift|Seats offered/)
})

test('staff transport coordination summary stays staff only and manually derived', async () => {
  const staffSource = await readFile(staffPageUrl, 'utf8')
  const parentSource = await readFile(parentPortalPageUrl, 'utf8')
  const confirmSource = await readFile(confirmFunctionUrl, 'utf8')
  const availabilityFunctionSource = await readFile(sendFunctionUrl, 'utf8')
  const helperStart = staffSource.indexOf('function getTransportCoordinationSummary')
  const helperEnd = staffSource.indexOf('function getAvailabilityStats', helperStart)
  const panelStart = staffSource.indexOf('function TransportCoordinationPanel')
  const panelEnd = staffSource.indexOf('function TransportCoordinationGroup', panelStart)
  const groupStart = staffSource.indexOf('function TransportCoordinationGroup')
  const groupEnd = staffSource.indexOf('function ReadinessItem', groupStart)

  assert.notEqual(helperStart, -1)
  assert.notEqual(helperEnd, -1)
  assert.notEqual(panelStart, -1)
  assert.notEqual(panelEnd, -1)
  assert.notEqual(groupStart, -1)
  assert.notEqual(groupEnd, -1)

  const helperSource = staffSource.slice(helperStart, helperEnd)
  const panelSource = staffSource.slice(panelStart, panelEnd)
  const groupSource = staffSource.slice(groupStart, groupEnd)

  assert.match(helperSource, /transportNeedsLift/)
  assert.match(helperSource, /transportCanOfferLift/)
  assert.match(helperSource, /transportSeatsOffered/)
  assert.match(helperSource, /transportRespondedAt/)
  assert.match(helperSource, /createTransportCoordinationGroup\('Needs lift', needsLift\)/)
  assert.match(helperSource, /createTransportCoordinationGroup\('Can offer seats', canOfferSeats\)/)
  assert.match(helperSource, /createTransportCoordinationGroup\('No response', noResponse\)/)
  assert.match(helperSource, /createTransportCoordinationGroup\('Maybe', maybe\)/)
  assert.match(helperSource, /createTransportCoordinationGroup\('Unavailable', unavailable\)/)
  assert.match(helperSource, /chaseList/)
  assert.match(helperSource, /seatsOffered - liftNeeds/)
  assert.match(panelSource, /Transport coordination/)
  assert.match(panelSource, /Staff-only/)
  assert.match(panelSource, /Manual coordination only/)
  assert.match(panelSource, /No matching has been created/)
  assert.match(panelSource, /Lift needs/)
  assert.match(panelSource, /Seats offered/)
  assert.match(panelSource, /Balance/)
  assert.match(staffSource, /Potential shortfall/)
  assert.match(staffSource, /Potential surplus/)
  assert.match(staffSource, /Capacity balanced/)
  assert.match(panelSource, /Staff chase list/)
  assert.match(groupSource, /getAvailabilityStatusLabel\(row\.status\)/)
  assert.doesNotMatch(helperSource, /fetch\(|localStorage|sessionStorage|supabase|insert|update|delete/)
  assert.doesNotMatch(panelSource, /fetch\(|localStorage|sessionStorage|supabase|insert|update|delete/)
  assert.doesNotMatch(groupSource, /recipientEmail|selectedByEmail|parentEmail|mailto:|tel:/)
  assert.doesNotMatch(panelSource, /recipientEmail|selectedByEmail|parentEmail|mailto:|tel:/)
  assert.doesNotMatch(parentSource, /Transport coordination/)
  assert.doesNotMatch(parentSource, /Manual coordination only/)
  assert.doesNotMatch(parentSource, /No matching has been created/)
  assert.doesNotMatch(parentSource, /Staff chase list/)
  assert.match(confirmSource, /Staff coordinate transport manually\. These answers are not shared with other parents\./)
  assert.match(confirmSource, /supabase\.rpc\('submit_match_day_availability_response'/)
  assert.match(availabilityFunctionSource, /\.from\('scheduled_email_queue'\)[\s\S]*\.insert\(/)
})

test('staff volunteer selection is resolved server side and queues notifications', async () => {
  const source = await readFile(selectVolunteerFunctionUrl, 'utf8')

  assert.match(source, /createPublicSupabaseClient\(event, \{\s+global:\s+\{\s+headers:\s+\{\s+Authorization: `Bearer \$\{token\}`/s)
  assert.match(source, /createSupabaseAdminClient\(event\)/)
  assert.match(source, /requestId = normalizeText\(body\.requestId\)/)
  assert.match(source, /\.from\('match_day_availability_requests'\)[\s\S]*\.eq\('id', requestId\)[\s\S]*\.eq\('match_day_id', match\.id\)/)
  assert.match(source, /parent_link_id, status, volunteer_scorer_response/)
  assert.match(source, /This volunteer response has expired\. Ask the parent to submit a fresh Match Day response\./)
  assert.match(source, /resolveParentLink\(adminSupabase, \{ match, request \}\)/)
  assert.match(source, /request\.parent_link_id/)
  assert.match(source, /normalizeEmail\(link\.email\) === requestEmail/)
  assert.match(source, /normalizeText\(player\?\.player_name\)\.toLowerCase\(\) === requestPlayerName/)
  assert.match(source, /\.from\('match_day_role_assignments'\)[\s\S]*\.upsert\(payload, \{ onConflict: 'match_day_id,role' \}\)[\s\S]*\.select\('\*, parent_player_links:parent_link_id \(email, auth_user_id, players:player_id \(player_name\)\)'\)[\s\S]*\.single\(\)/)
  assert.match(source, /savedAssignment = await upsertRoleAssignment\(adminSupabase, \{ match, parentLink, profile, role \}\)/)
  assert.match(source, /assignment: selected \? savedAssignment : null/)
  assert.match(source, /assignmentId: savedAssignment\?\.id \|\| ''/)
  assert.match(source, /removedRole: selected \? '' : role/)
  assert.match(source, /resolveRequestScopedParentLink\(adminSupabase, \{ baseSelect, match, request \}\)/)
  assert.match(source, /assertParentLinkMatchesVolunteerResponse\(\{ match, parentLink: data, request \}\)/)
  assert.match(source, /This volunteer could not be assigned because the parent link does not match the response contact\./)
  assert.match(source, /\.from\('match_day_scorer_assignments'\)[\s\S]*\.delete\(\)[\s\S]*\.eq\('match_day_id', match\.id\)/)
  assert.match(source, /\.from\('scheduled_email_queue'\)[\s\S]*\.insert\(/)
  assert.match(source, /resendPayload/)
  assert.match(source, /visibleInEmailQueue: false/)
  assert.match(source, /purpose: 'role_selection_notification'/)
  assert.match(source, /formatDate\(match\.match_date\)/)
  assert.match(source, /getNextGoogleDatePart/)
  assert.match(source, /View in Parent Portal/)
  assert.match(source, /Add to calendar/)
  assert.match(source, /clubs:club_id \(name, logo_url\)/)
  assert.match(source, /requiredFeature: 'parentEmails'/)
  assert.match(source, /Volunteer selection was saved, but notification email could not be queued\./)
  assert.doesNotMatch(source, /SUPABASE_SERVICE_ROLE_KEY/)
})
